# Default values for accusation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: mungta

nameOverride: ""
fullnameOverride: accusation

selectorLabels: accusation

replicaCount: 1
revisionHistoryLimit: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

image:
  repository: -.azurecr.io/-
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "32"

resources:
  requests:
    cpu: 200m
  limits:
    cpu: 500m

env:
  configMap:
    name: accusation-config
  secret:
    name: mungta-credentials

config:
  logLevel: debug
  dbHost: -.mysql.database.azure.com
  kafka: kafka.kafka.svc.cluster.local:9092

livenessProbe:
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 120
  periodSeconds: 60
readinessProbe:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 60

securityContext:
  privileged: false

blueGreen:
  autoPromotion: true

service:
  type: ClusterIP
  port: 8080

logVolume:
  name: log-volume
  path: /var/log/containers
  type: DirectoryOrCreate

circuit:
  enabled: false
  tcp:
    connection: 10
  http:
    maxPending: 5
    connection: 10
  interval: 10s
  consecutive5xxErrors: 3
  baseEjectionTime: 3m
  maxEjectionPercent: 100

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
