apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  log-level: {{ .Values.config.logLevel }}
  db-host: {{ .Values.config.dbHost }}
  kafka-broker: {{ .Values.config.kafka }}
