apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-username: {{ .Values.config.db.userName }}
  db-password: {{ .Values.config.db.password }}
  mail-username: {{ .Values.config.mail.userName }}
  mail-password: {{ .Values.config.mail.password }}
  